config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  
  resources :users
  root "tweets#index"
  resources :tweets
  post 'top/login'
  get 'top/logout'
  post 'top/logout'
  get 'top/main'
  get 'top/login_form'
  post "likes/create"
  get "likes/destroy"
  resources :likes, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :tweet
end

app/models/profile.rb
class Profile < ApplicationRecord
    belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    has_many :likes, dependent: :destroy
    has_many :like_users, through: :likes, source: :user
    
    def like(user)
        likes.create(user_id: user.id)
    end
    
    def unlike(user)
        likes.find_by(user_id: user.id).destroy
    end

    def liked?(user) #いいね済みか調べる(true / false)
        like_users.include?(user)
    end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :tweets, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :like_tweets, through: :likes, source: :tweet
    
    validates :password, presence: true, confirmation: true
    
    attr_accessor :password, :password_confirmation

    def password=(val)
        if val.present?
            self.pass = BCrypt::Password.create(val)
        end
        @password = val
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    private
        def current_user
            if session[:login_uid]
                User.find_by(uid: session[:login_uid])
            end
        end
end 

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        tweet = Tweet.find(params[:tweet_id])
        unless tweet.liked?(current_user)
            tweet.like(current_user)
        end
        redirect_to root_path
    end
    
    def destroy
        tweet = Tweet.find(params[:tweet_id])
        if tweet.liked?(current_user)
            tweet.unlike(current_user)
        end
        redirect_to root_path
    end
end

app/controllers/top_controller.rb
require 'bcrypt'

class TopController < ApplicationController
    def main
        render "login_form"
    end

    def login
        user = User.find_by(uid: params[:uid])
        login_password = BCrypt::Password.new(user.pass)
        if login_password == params[:pass]
            session[:login_uid] = params[:uid]
            redirect_to root_path
        end
    end
    
    def logout
        logger.debug(session[:login_uid])
        session[:login_uid] = nil
        redirect_to root_path
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    def index
      @tweets = Tweet.all
    end
    
    def new
      @tweet = Tweet.new
    end
    
    
    def create
      @tweet = Tweet.create(message: params[:tweet][:message])
      @tweet.user = current_user
      @tweet.save
      redirect_to root_path
    end
    
    def destroy
      tweet = Tweet.find(params[:id])
      tweet.destroy
      redirect_to root_path
    end
end

app/controllers/users_controller.rb
require 'bcrypt'

class UsersController < ApplicationController
    def index
        @users = User.all
    end
    
    def new
        @user = User.new
    end
    
    def create
        #if not User.find_by(uid: params[:user][:uid])
        #    pass = params[:user][:pass]
        #    hashpass = BCrypt::Password.create(pass)
        #    @user = User.new(uid: params[:user][:uid], pass: hashpass)
        #    @user.save
        #end
        #redirect_to root_path
        @user = User.new(
            uid: params[:user][:uid],
            password: params[:user][:password],
            password_confirmation: params[:user][:password_confirmation])
        if @user.save
            redirect_to users_path
        else
            render 'new'
        end
    end
    
    def destroy
        user = User.find(params[:id])
        user.destroy
        redirect_to root_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L5</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/login_form.html.erb
<%= form_tag '/top/login', method: :post do %>
  <%= label_tag :uid, 'ユーザーID' %>
  <%= text_field_tag :uid %>
  <%= label_tag :pass, 'パスワード' %>
  <%= password_field_tag :pass %>
  <%= submit_tag '登録' %>
<% end %>

app/views/top/main.html.erb
<%#=link_to 'ツイート一覧', controller: "tweets", action: "index" %><br>
<%#=link_to 'ユーザ一覧', controller: "users", action: "index" %><br>

<%#= link_to "ログイン", top_login_form_path, method: :post %><br>
<%#= link_to "ログアウト", action: "logout", method: :post %>

<%#= link_to "ログインチェック", action: "login_check", method: :post %>

app/views/tweets/index.html.erb
<% if session[:login_uid] != nil %>
  <%=link_to 'ツイートする', new_tweet_path, data: { method: :get } %>
<% end %>

<% @tweets.each do |e| %>
  <p>
      <%= e.message %>
      <% if session[:login_uid] != nil %>
        <%=link_to '削除', tweet_path(e), data: { turbo_method: :delete } %>
        <% if e.liked?(current_user) %>
          <%= link_to 'いいね削除', like_path(tweet_id: e.id), method: :delete %>
        <% else %>
          <%= link_to 'いいね', likes_path(tweet_id: e.id), data: {turbo_method: :post} %>
        <% end %>
      <% end %>
  </p>
<% end %>

<%=link_to 'ユーザ一覧', controller: "users", action: "index" %><br>
<% if session[:login_uid] == nil %>
  <%= link_to "ログイン", controller: "top",  action: "main", method: :post %><br>
<% else %>
  <%= link_to "ログアウト", controller: "top",  action: "logout", method: :post %><br><br><br>
<% end %>

<%= session[:login_uid] %>
<p>でログイン中</p>

app/views/tweets/new.html.erb
<%= form_for @tweet , url: {action: :create} do |f| %>
    <%= f.label :message, 'メッセージ' %>
    <%= f.text_field :message %>
    <%= f.submit 'ツイートする' %>
<% end %>

app/views/users/index.html.erb
<%=link_to 'ユーザ登録', new_user_path, data: { method: :get } %>

<% @users.each do |e| %>
  <p>
      <%= e.uid %>
      <%=link_to '削除', user_path(e), data: { turbo_method: :delete } %>
  </p>
<% end %>

<%=link_to 'ホーム', root_path  %>

app/views/users/new.html.erb
<%= form_for @user , url: {action: :create} do |f| %>
    <%= f.label :uid, 'ユーザID' %>
    <%= f.text_field :uid %>
    <%= f.label :password, 'パスワード' %>
    <%= f.password_field :password %>
    <%= f.label :password_confirmation, 'パスワード(確認)' %>
    <%= f.password_field :password_confirmation %>
    <%= f.submit '登録' %>
<% end %>